# 1️⃣ JDK 17 환경에서 /whatap 폴더 생성
FROM ncp-vsaidt-registry.ncr.gov-ntruss.com/openjdk:17.0.1-jdk-slim AS whatap_builder

# 2️⃣ JDK 8 환경에서 Gradle 빌드 및 실행
FROM ncp-vsaidt-registry.ncr.gov-ntruss.com/openjdk:8 AS builder

COPY . /tmp
WORKDIR /tmp

# Gradle 빌드 수행 (JDK 8 환경에서 실행)
RUN chmod +x ./gradlew
RUN ./gradlew clean buildDependents

# 3️⃣ 최종 실행 환경 (Tomcat 8.5 + JDK 8)
FROM tomcat:8.5-jdk8-corretto

# Gradle 빌드 결과물 (WAR 파일) 복사
COPY --from=builder /tmp/build/libs/vivasam-mobile-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
COPY --from=whatap_builder /whatap /whatap

# 필요한 디렉토리 생성
RUN mkdir -p /media/vivasam-162 /media/VIVASAM /media/VISANG /iBookSam
RUN chmod 755 /media/vivasam-162 /media/VIVASAM /media/VISANG /iBookSam

RUN chown -R 1000:1000 /usr/local/tomcat
RUN find /usr/local/tomcat/conf/ -type f -exec chmod 640 {} \;
RUN chmod 600 /usr/local/tomcat/conf/tomcat-users.xml

EXPOSE 8080
CMD ["catalina.sh", "run"]
