import React from "react";


export {default as TermsService} from './TermsService'
export {default as TermsPrivacy} from './TermsPrivacy'
export {default as TermsServicePopupHistory} from './TermsServicePopupHistory'
export {default as TermsPrivacyPopupHistory} from './TermsPrivacyPopupHistory'

export {default as Access_viva_1} from './history/service/Access_viva_1'
export {default as Access_viva_2} from './history/service/Access_viva_2'
export {default as Access_viva_3} from './history/service/Access_viva_3'
export {default as Access_viva_4} from './history/service/Access_viva_4'
export {default as Access_viva_5} from './history/service/Access_viva_5'
export {default as Access_viva_6} from './history/service/Access_viva_6'
export {default as Access_tsc_1} from './history/service/Access_tsc_1'
export {default as Access_tsc_2} from './history/service/Access_tsc_2'
export {default as Access_tsc_3} from './history/service/Access_tsc_3'
export {default as Access_tsc_4} from './history/service/Access_tsc_4'
export {default as Access_tsc_5} from './history/service/Access_tsc_5'
export {default as Access_tsc_6} from './history/service/Access_tsc_6'
export {default as Access_sso_1} from './history/service/Access_sso_1'
export {default as Access_sso_2} from './history/service/Access_sso_2'
export {default as Access_sso_3} from './history/service/Access_sso_3'
export {default as Access_sso_4} from './history/service/Access_sso_4'
export {default as Access_sso_5} from './history/service/Access_sso_5'
export {default as Access_sso_6} from './history/service/Access_sso_6'
export {default as Access_sso_7} from './history/service/Access_sso_7'

export {default as Privacy_viva_1} from './history/privacy/Privacy_viva_1'
export {default as Privacy_viva_2} from './history/privacy/Privacy_viva_2'
export {default as Privacy_viva_3} from './history/privacy/Privacy_viva_3'
export {default as Privacy_viva_4} from './history/privacy/Privacy_viva_4'
export {default as Privacy_viva_5} from './history/privacy/Privacy_viva_5'
export {default as Privacy_viva_6} from './history/privacy/Privacy_viva_6'
export {default as Privacy_viva_7} from './history/privacy/Privacy_viva_7'
export {default as Privacy_viva_8} from './history/privacy/Privacy_viva_8'
export {default as Privacy_viva_9} from './history/privacy/Privacy_viva_9'
export {default as Privacy_viva_10} from './history/privacy/Privacy_viva_10'
export {default as Privacy_viva_11} from './history/privacy/Privacy_viva_11'
export {default as Privacy_viva_12} from './history/privacy/Privacy_viva_12'
export {default as Privacy_viva_13} from './history/privacy/Privacy_viva_13'
export {default as Privacy_viva_14} from './history/privacy/Privacy_viva_14'
export {default as Privacy_tsc_1} from './history/privacy/Privacy_tsc_1'
export {default as Privacy_tsc_2} from './history/privacy/Privacy_tsc_2'
export {default as Privacy_tsc_3} from './history/privacy/Privacy_tsc_3'
export {default as Privacy_tsc_4} from './history/privacy/Privacy_tsc_4'
export {default as Privacy_tsc_5} from './history/privacy/Privacy_tsc_5'
export {default as Privacy_tsc_6} from './history/privacy/Privacy_tsc_6'
export {default as Privacy_tsc_7} from './history/privacy/Privacy_tsc_7'
export {default as Privacy_tsc_8} from './history/privacy/Privacy_tsc_8'
export {default as Privacy_tsc_9} from './history/privacy/Privacy_tsc_9'
export {default as Privacy_tsc_10} from './history/privacy/Privacy_tsc_10'
export {default as Privacy_tsc_11} from './history/privacy/Privacy_tsc_11'
export {default as Privacy_tsc_12} from './history/privacy/Privacy_tsc_12'
export {default as Privacy_tsc_13} from './history/privacy/Privacy_tsc_13'
export {default as Privacy_tsc_14} from './history/privacy/Privacy_tsc_14'
export {default as Privacy_tsc_15} from './history/privacy/Privacy_tsc_15'
export {default as Privacy_tsc_16} from './history/privacy/Privacy_tsc_16'

export {default as Total_privacy_ver1} from './history/privacy/Total_privacy_ver1'
export {default as Total_privacy_ver2} from './history/privacy/Total_privacy_ver2'
export {default as Total_privacy_ver3} from './history/privacy/Total_privacy_ver3'
export {default as Total_privacy_ver4} from './history/privacy/Total_privacy_ver4'
export {default as Total_privacy_ver5} from './history/privacy/Total_privacy_ver5'
export {default as Total_privacy_ver6} from './history/privacy/Total_privacy_ver6'