-- =============================================
-- Author:		심원보
-- Create date: 2016-08-31
-- Description:	비비샘 > 이벤트 > 이벤트 리스트
-- EXEC SP_EVENT_INFO_2016_LIST 1, 10, '', '', 166
-- =============================================
create PROCEDURE [dbo].[SP_EVENT_INFO_2016_LIST]
@P_PAGE_NO			INT = 1,
@P_PAGE_SIZE		INT = 10,
@P_SCHTYPE			VARCHAR(10) = NULL,
@P_KEYWORD			NVARCHAR(100) = NULL,
@P_EVENT_ID			INT = NULL
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- SET NOCOUNT ON added to prevent extra result sets from
-- interfering with SELECT statements.
SET NOCOUNT ON;

DECLARE @TEMPTABLE_DATA TABLE
(
SEQ						INT PRIMARY KEY
,EVENT_ID				INT
,EVENT_REGDATE			DATETIME
)

DECLARE   @ROW_TOTAL  int --전체 Row 수
DECLARE   @ROW_MAX    nvarchar(10) --조회할 Row 수 중 최대 Row수
DECLARE   @ROW_MIN    nvarchar(10) --조회할 Row수 중 최소 Row수
DECLARE   @PAGE_TOTAL int --전체 페이지 수

INSERT @TEMPTABLE_DATA
SELECT
  ROW_NUMBER() OVER(ORDER BY EV.EVENT_ID DESC) AS seq,
  EV.EVENT_ID       AS event_id,
  EV.EVENT_REGDATE  AS EVENT_REGDATE
FROM DBO.EVENT_INFO AS EV
WHERE 1 = 1
  AND ((ISNULL(@P_EVENT_ID, '') != '' AND EV.EVENT_ID = @P_EVENT_ID)
  OR (ISNULL(@P_EVENT_ID, '') = '' AND 1 = 1))
  AND EVENT_DEL_YN = 'N'
  AND EVENT_PARENT_ID IS NULL /*부모 이벤트 ID에 대해서만 조회*/
  AND ((ISNULL(@P_KEYWORD, '') != '' AND EV.EVENT_NAME LIKE '%' + @P_KEYWORD + '%')
  OR (ISNULL(@P_KEYWORD, '') = '' AND 1 = 1))


  SET @ROW_TOTAL = @@ROWCOUNT

  -- 총페이지 수
  IF @ROW_TOTAL % @P_PAGE_SIZE = 0
SET @PAGE_TOTAL = @ROW_TOTAL/@P_PAGE_SIZE
    ELSE
SET @PAGE_TOTAL = (@ROW_TOTAL/@P_PAGE_SIZE) + 1

SET @ROW_MIN = (@P_PAGE_NO-1) * @P_PAGE_SIZE + 1
SET @ROW_MAX = @P_PAGE_NO * @P_PAGE_SIZE ;

WITH EVENT_APPLY_CNT_INFO AS (
--참여자 정보
SELECT TOP 5
EI.EVENT_PARENT_ID,
EI.EVENT_ID,
EI.EVENT_NAME,
COUNT(EJ.EVENT_ID) AS CNT
FROM @TEMPTABLE_DATA AS TD
JOIN dbo.EVENT_INFO AS EI ON EI.EVENT_PARENT_ID = TD.EVENT_ID --AND EI.EVENT_PARENT_ID IS NOT NULL
LEFT JOIN dbo.EVENT_JOIN AS EJ ON EJ.EVENT_ID = EI.EVENT_ID
LEFT JOIN dbo.MEMBER AS M ON M.MEMBER_ID = EJ.MEMBER_ID AND M.[STATE] != 'D' --탈퇴 회원 제외
WHERE EI.EVENT_DEL_YN = 'N'
GROUP BY EI.EVENT_PARENT_ID, EI.EVENT_ID, EI.EVENT_NAME
ORDER BY EI.EVENT_ID
)
SELECT
  0 AS seq,
  CAST(@ROW_TOTAL as VARCHAR) AS event_id,
  CAST(@PAGE_TOTAL as NVARCHAR) AS event_name,
  CAST(@P_PAGE_SIZE as NVARCHAR) AS event_bn_sav,
  NULL AS event_bn_path,
  NULL AS event_sdate,
  NULL AS event_edate,
  NULL AS event_pdate,
  NULL AS event_regid,
  NULL AS event_use_yn,
  NULL AS event_regdate,
  NULL AS child_event_id,
  NULL AS child_event_name,
  NULL AS event_join_cnt,
  NULL AS event_join_mob_cnt,
  NULL AS event_state_desc
UNION ALL
SELECT
  T.SEQ,
  T.EVENT_ID,
  EI.EVENT_NAME,
  EI.EVENT_BN_SAV,
  EI.EVENT_BN_PATH,
  CAST(EI.EVENT_SDATE AS DATE),
  CAST(EI.EVENT_EDATE AS DATE),
  CAST(EI.EVENT_PDATE AS DATE),
  EI.EVENT_REGID,
  EI.EVENT_USE_YN,
  CONVERT(VARCHAR(10), EI.EVENT_REGDATE, 121) AS EVENT_REGDATE,
  EACI.EVENT_ID AS CHILD_EVENT_ID,
  EACI.EVENT_NAME AS CHILD_EVENT_NAME,
  ISNULL(CASE WHEN EACI.EVENT_PARENT_ID IS NOT NULL THEN EACI.CNT ELSE PE.CNT END, 0) AS event_join_cnt,
  ISNULL(CASE WHEN EACI.EVENT_PARENT_ID IS NOT NULL THEN EACI.CNT ELSE PE2.CNT END, 0) AS event_join_mob_cnt,
  CASE WHEN EI.EVENT_SDATE <= GETDATE() AND EI.EVENT_EDATE >= GETDATE() THEN '진행중'
       WHEN EI.EVENT_SDATE > GETDATE() THEN '대기'
       WHEN EI.EVENT_EDATE < GETDATE() THEN '종료' END AS event_state_desc
FROM @TEMPTABLE_DATA AS T
       JOIN dbo.EVENT_INFO AS EI ON T.EVENT_ID = EI.EVENT_ID
       LEFT JOIN EVENT_APPLY_CNT_INFO AS EACI ON EACI.EVENT_PARENT_ID = T.EVENT_ID
     OUTER APPLY (
     SELECT
     EJ.EVENT_ID,
     COUNT(EJ.EVENT_ID) AS CNT
     FROM dbo.EVENT_JOIN AS EJ
     WHERE EJ.EVENT_ID = T.EVENT_ID AND VIA <> 'MOBILE'
     GROUP BY EJ.EVENT_ID
  ) AS PE
     OUTER APPLY (
     SELECT
     EJ.EVENT_ID,
     COUNT(EJ.EVENT_ID) AS CNT
     FROM dbo.EVENT_JOIN AS EJ
     WHERE EJ.EVENT_ID = T.EVENT_ID AND VIA = 'MOBILE'
     GROUP BY EJ.EVENT_ID
  ) AS PE2
WHERE T.SEQ BETWEEN (@P_PAGE_NO-1) * @P_PAGE_SIZE + 1 AND @P_PAGE_NO * @P_PAGE_SIZE

END



go

