USE [vivasam_mobile]
GO

/****** Object:  Table [dbo].[APP_NOTIFICATION_LOGS]    Script Date: 2019-01-19 오후 1:14:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_NOTIFICATION_LOGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MEMBER_ID] [varchar](30) NOT NULL,
	[MESSAGE_ID] [int] NOT NULL,
	[REGDATE] [datetime] NULL,
	[STATUS] [varchar](20) NOT NULL,
 CONSTRAINT [PK_APP_NOTIFICATION_FAILED_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[APP_NOTIFICATION_LOGS] ADD  CONSTRAINT [DF_APP_NOTIFICATION_FAILED_LOG_REGDATE]  DEFAULT (getdate()) FOR [REGDATE]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'전송 상태. SUCCESS, FAILED 중 하나.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'APP_NOTIFICATION_LOGS', @level2type=N'COLUMN',@level2name=N'STATUS'
GO


CREATE NONCLUSTERED INDEX [IX_APP_NOTIFICATION_LOGS_01] ON [dbo].[APP_NOTIFICATION_LOGS]
(
	[MEMBER_ID] ASC,
	[STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO